/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/wallE.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/wallE.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="body" geometry={nodes.body.geometry} material={materials.Material_0} position={[3.269, 0, -3.231]} />
      <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[0, -1.025, 0]} scale={17.987} />
      <group name="head" position={[3.278, 0.289, -3.392]} scale={0.055}>
        <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['Material.004']} />
        <mesh name="Sphere002_1" geometry={nodes.Sphere002_1.geometry} material={materials['Material.005']} />
        <mesh name="Sphere002_2" geometry={nodes.Sphere002_2.geometry} material={materials.Material_0} />
      </group>
      <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} position={[3.262, 0.018, -3.249]} scale={[1, 0.461, 1]} />
    </group>
  )
}

useGLTF.preload('/wallE.glb')
